from enum import StrEnum


class PermissionCode(StrEnum):
	CREATE_USER = "CREATE_USER"
	BLOCK_USER = "BLOCK_USER"
	UNBLOCK_USER = "UNBLOCK_USER"
	DELETE_USER = "DELETE_USER"

	CREATE_EMPLOYEE = "CREATE_EMPLOYEE"
	HIRE_EMPLOYEE = "HIRE"
	FIRE_EMPLOYEE = "FIRE"

	CREATE_PERMISSION = "CREATE_PERMISSION"
	ASSIGN_PERMISSION = "ASSIGN_PERMISSION"
	UNASSIGN_PERMISSION = "UNASSIGN_PERMISSION"
	DEACTIVATE_PERMISSION = "DEACTIVATE_PERMISSION"
	SET_PERMISSION_DESCRIPTION = "SET_PERMISSION_DESCRIPTION"
	
	CREATE_ROLE = "CREATE_ROLE"
	DEACTIVATE_ROLE = "DEACTIVATE_ROLE"
	ASSIGN_ROLE = "ASSIGN_ROLE"
	UNASSIGN_ROLE = "UNASSIGN_ROLE"

	CREATE_CATEGORY = "CREATE_CATEGORY"
	DEACTIVATE_CATEGORY = "DEACTIVATE_CATEGORY"
	SET_CATEGORY_PARENT = "SET_CATEGORY_PARENT"

	CREATE_ORDER_FULFILLMENT = "CREATE_ORDER_FULFILLMENT"
	CREATE_ORDER_FULFILLMENT_ITEM = "CREATE_ORDER_FULFILLMENT_ITEM"

	CREATE_WAREHOUSE = "CREATE_WAREHOUSE"
	DELETE_WAREHOUSE = "DELETE_WAREHOUSE"
	SET_WAREHOUSE_DESCRIPTION = "SET_WAREHOUSE_DESCRIPTION"
	ADD_WAREHOUSE_PRODUCT = "ADD_WAREHOUSE_PRODUCT"
	DELETE_WAREHOUSE_PRODUCT = "DELETE_WAREHOUSE_PRODUCT"

	CREATE_PRODUCT = "CREATE_PRODUCT"
	DELETE_PRODUCT = "DELETE_PRODUCT"
	SET_PRODUCT_PRICE = "SET_PRODUCT_PRICE"
	SET_PRODUCT_DESCRIPTION = "SET_PRODUCT_DESCRIPTION"
	ASSIGN_PRODUCT_CATEGORY = "ASSIGN_PRODUCT_CATEGORY"
	UNASSIGN_PRODUCT_CATEGORY = "UNASSIGN_PRODUCT_CATEGORY"
	CREATE_PRODUCT_IMAGE = "CREATE_PRODUCT_IMAGE"
	DELETE_PRODUCT_IMAGE = "DELETE_PRODUCT_IMAGE"

	CREATE_SUPPLIER = "CREATE_SUPPLIER"
	DEACTIVATE_SUPPLIER = "DEACTIVATE_SUPPLIER"
	SET_SUPPLIER_FIELDS = "SET_SUPPLIER_FIELDS"

	CREATE_SUPPLY = "CREATE_SUPPLY"
	SET_SUPPLY_STATUS = "SET_SUPPLY_STATUS"

	CREATE_SUPPLY_ITEM = "CREATE_SUPPLY_ITEM"
	DELETE_SUPPLY_ITEM = "DELETE_SUPPLY_ITEM"

	SET_ORDER_STATUS = "SET_ORDER_STATUS"

	CREATE_WRITE_OFF = "CREATE_WRITE_OFF"
	DELETE_WRITE_OFF = "DELETE_WRITE_OFF"

	CREATE_WRITE_OFF_ITEM = "CREATE_WRITE_OFF_ITEM"
	DELETE_WRITE_OFF_ITEM = "DELETE_WRITE_OFF_ITEM"

	DELETE_PRODUCT_REVIEW = "DELETE_PRODUCT_REVIEW"
